-- Tạo bảng LoaiVT
CREATE TABLE LoaiVT (
    MaLVT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenLVT VARCHAR2(100) NOT NULL
);

-- Tạo bảng NhaCungCap
CREATE TABLE NhaCungCap (
    MaNCC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNCC VARCHAR2(100) NOT NULL
);

-- Tạo bảng KhachHang
CREATE TABLE KhachHang (
    MaKH NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenKH VARCHAR2(100) NOT NULL,
    SDT NUMBER(15)
);

-- Tạo bảng NhanVien
CREATE TABLE NhanVien (
    MaNV NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNV VARCHAR2(100) NOT NULL,
    NgayVaoLam DATE,
    Luong NUMBER,
    ChucVu VARCHAR2(50) NOT NULL,
    CONSTRAINT CK_ChucVu CHECK (ChucVu IN ('KeToan', 'NhapXuat', 'NghiemThu'))
);

-- Tạo bảng NhaVanChuyen
CREATE TABLE NhaVanChuyen (
    MaNVC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNVC VARCHAR2(100) NOT NULL,
    SDT_DaiDien VARCHAR2(15)
);

-- Tạo bảng VatTu
CREATE TABLE VatTu (
    MaVT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenVT VARCHAR2(100) NOT NULL,
    MaLVT NUMBER NOT NULL,
    DonGiaNhap NUMBER NOT NULL,
    DonGiaXuat NUMBER,
    SoLuong NUMBER DEFAULT 0,
    TrangThai NUMBER CONSTRAINT CK_TrangThai CHECK(TrangThai Between 0 and 2),
    CONSTRAINT FK_VatTu_LoaiVT FOREIGN KEY (MaLVT) REFERENCES LoaiVT(MaLVT)
);

-- Tạo bảng GiaoDich
CREATE TABLE GiaoDich (
    MaGD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LoaiGD VARCHAR2(10) NOT NULL,
    ThoiGian DATE DEFAULT SYSDATE,
    ThanhTien NUMBER DEFAULT 0,
    MaNVC NUMBER NOT NULL,
    CONSTRAINT CK_GiaoDich_LoaiGD CHECK (LoaiGD IN ('Nhap', 'Xuat')),
    CONSTRAINT FK_GiaoDich_NhaVanChuyen FOREIGN KEY (MaNVC) REFERENCES NhaVanChuyen(MaNVC)
);

-- Tạo bảng LichSuCapNhat
CREATE TABLE LichSuCapNhat (
    MaLSCN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaVT NUMBER NOT NULL,
    GiaCu NUMBER,
    GiaMoi NUMBER NOT NULL,
    NgayCapNhat DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LichSuCapNhat_VatTu FOREIGN KEY (MaVT) REFERENCES VatTu(MaVT)
);

-- Tạo bảng CT_Nhap
CREATE TABLE CT_Nhap (
    MaGD NUMBER NOT NULL,
    MaVT NUMBER NOT NULL,
    SL NUMBER NOT NULL,
    MaNV NUMBER NOT NULL,
    ThanhTien NUMBER,
    MaNCC NUMBER NOT NULL,
    CONSTRAINT PK_CT_Nhap PRIMARY KEY (MaGD, MaVT),
    CONSTRAINT FK_CT_Nhap_GiaoDich FOREIGN KEY (MaGD) REFERENCES GiaoDich(MaGD),
    CONSTRAINT FK_CT_Nhap_VatTu FOREIGN KEY (MaVT) REFERENCES VatTu(MaVT),
    CONSTRAINT FK_CT_Nhap_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    CONSTRAINT FK_CT_Nhap_NhaCungCap FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

-- Tạo bảng CT_Xuat
CREATE TABLE CT_Xuat (
    MaGD NUMBER NOT NULL,
    MaVT NUMBER NOT NULL,
    SL NUMBER NOT NULL,
    MaNV NUMBER NOT NULL,
    ThanhTien NUMBER,
    MaKH NUMBER NOT NULL,
    CONSTRAINT PK_CT_Xuat PRIMARY KEY (MaGD, MaVT),
    CONSTRAINT FK_CT_Xuat_GiaoDich FOREIGN KEY (MaGD) REFERENCES GiaoDich(MaGD),
    CONSTRAINT FK_CT_Xuat_VatTu FOREIGN KEY (MaVT) REFERENCES VatTu(MaVT),
    CONSTRAINT FK_CT_Xuat_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    CONSTRAINT FK_CT_Xuat_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

-- Tạo bảng LichSuKiemKe
CREATE TABLE LichSuKiemKe (
    MaLSKK NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaNV NUMBER NOT NULL,
    ThoiGian DATE DEFAULT SYSDATE,
    MaVT NUMBER NOT NULL,
    TinhTrang VARCHAR2(100),
    CONSTRAINT FK_LichSuKiemKe_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    CONSTRAINT FK_LichSuKiemKe_VatTu FOREIGN KEY (MaVT) REFERENCES VatTu(MaVT)
);


-- Xóa các bảng có phụ thuộc khóa ngoại trước
--DROP TABLE CT_Xuat CASCADE CONSTRAINTS;
--DROP TABLE CT_Nhap CASCADE CONSTRAINTS;
--DROP TABLE LichSuCapNhat CASCADE CONSTRAINTS;
--DROP TABLE LichSuKiemKe CASCADE CONSTRAINTS;
--DROP TABLE GiaoDich CASCADE CONSTRAINTS;
--DROP TABLE VatTu CASCADE CONSTRAINTS;
--DROP TABLE NhanVien CASCADE CONSTRAINTS;
--DROP TABLE KhachHang CASCADE CONSTRAINTS;
--DROP TABLE NhaCungCap CASCADE CONSTRAINTS;
--DROP TABLE NhaVanChuyen CASCADE CONSTRAINTS;
--DROP TABLE LoaiVT CASCADE CONSTRAINTS;
